sudo: required
services:
  - docker

before_install:
  - docker build -t aminvdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run aminvdocker/react-test nmp test -- --coverage

after_success:
  - docker build -t aminvdocker/multi-client ./client
  - docker build -t aminvdocker/multi-nginx ./nginx
  - docker build -t aminvdocker/multi-server ./server
  - docker build -t aminvdocker/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push aminvdocker/multi-client
  - docker push aminvdocker/multi-nginx
  - docker push aminvdocker/multi-server
  - docker push aminvdocker/multi-worker